package:
  tags:
    - spikerguy-honeycomb
  script:
    - export PKG=${PWD##*/}
    - cd ..
    - sudo chrootbuild -cp $PKG
    - mv -v ./*.pkg.tar.* $PKG
  artifacts:
    paths:
    - ./*.pkg.tar.*
    expire_in: 1 week 

