on: [push, pull_request]

jobs:
  aarch64_job:
    runs-on: ubuntu-18.04
    name: Build on aarch64
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu18.04
          shell: /bin/sh
          install: |
            pacman -Syyu --noconfirm
            pacman -S git which --noconfirm
            pacman -S makepkg
          build:
            makepkg

