on: [push, pull_request]

jobs:
  aarch64_job:
    runs-on: ubuntu-18.04
    name: Build on aarch64
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: uraimo/run-on-arch-action@v1.0.8
      - uses: FFY00/build-arch-package@v1
        id: runmakepkg
        with:
          architecture: aarch64
          distribution: ubuntu18.04
          PKGBUILD: PKGBUILD
          OUTDIR: $HOME/linux-odroid-kernel
