name: Build kernel

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run aarch64..
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v1.0.8
      id: runcmd
        with:
          architecture: aarch64
          distribution: ubuntu-latest
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
      - name: Get the output
        run: |
            echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
