on: [push, pull_request]

jobs:
  aarch64_job:
    runs-on: ubuntu-18.04
    name: Build on aarch64
    steps:
      - uses: actions/checkout@2
      - uses: uraimo/run-on-arch-action@2
        id: runmakepkg
        with:
          architecture: aarch64
          distribution: ubuntu18.04
          shell: /bin/sh
          install: |
            pacman -Syyu --noconfirm
            pacman -S git which --noconfirm
            pacman -S makepkg
          build:
            makepkg

