on: [push, pull_request]

jobs:
  build_job:
    runs-on: ubuntu-18.04
    name: Build on archarm_latest aarch64

    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Build artifact
        id: build
        with:
          arch: aarch64
          distro: archarm_latest

          githubToken: ${{ secrets.GIT_TK }}

          setup: |
            mkdir -p "${PWD}/artifacts"

          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"

          shell: /bin/sh

          install: |
            pacman -Syyuu --noconfirm && pacman -S git which base-devel binutils make gcc pkg-config fakeroot coreutils kmod mkinitcpio>=0.7 fbset uboot-tools crda xmlto docbook-xsl kmod inetutils bc --noconfirm

          run: |
            useradd -m -G wheel -s /bin/bash user
            sudo chown -R user .
            echo "Makepkg started.."
            sudo -u user makepkg
            #echo 123 > filename.tar.zst
            ls
            cp -rf *.tar.zst "/artifacts"
            #cp $(which git) "/artifacts"
            echo "Produced artifact at /artifacts"
            echo "Success!"

      - name: Show the artifact
        run: |
          ls -al "${PWD}/artifacts/"

      - name: Upload the artifact
        uses: ncipollo/release-action@main
        with:
          tag: linux-odroid-bcdev_1.0
          allowUpdates: true
          artifacts: "${PWD}/artifacts/"
          body: |
            linux-odroid (aarch64) fork with binder & ashem support
          token: ${{ secrets.GIT_TK }}
